Update create_pr3.yml

diff --git a/.github/workflows/create_pr3.yml b/.github/workflows/create_pr3.yml
--- a/.github/workflows/create_pr3.yml
+++ b/.github/workflows/create_pr3.yml
@@ -24,25 +24,25 @@ jobs:
       # Step 3: Check out the main branch and pull the latest changes
       - name: Check out main branch
         run: |
-          git checkout main
-          git pull origin main
+          git checkout master
+          git pull origin master
 
       # Step 4: Check out the production branch and pull the latest changes
       - name: Check out production branch
         run: |
-          git checkout branch_for_release_test
-          git pull origin branch_for_release_test
+          git checkout production
+          git pull origin production
 
       # Step 5: Merge changes from the main branch into the production branch
       - name: Merge main branch into production
         run: |
-          git merge main || { echo 'Merge failed'; exit 1; }
+          git merge master || { echo 'Merge failed'; exit 1; }
 
       # Step 6: Push the merged changes to the production branch if merge was successful
       - name: Push changes to production branch
         if: success()
         run: |
-          git push origin branch_for_release_test
+          git push origin production
 
       # Step 7: Create a pull request to merge main into production
       - name: Create a pull request
@@ -52,5 +52,5 @@ jobs:
           token: ${{ secrets.GITHUB_TOKEN }} # GitHub token for authentication
           title: 'Release Merge: ${{ github.event.release.tag_name }}' # Title of the pull request
           body: 'This pull request merges the main branch into the production branch.' # Body content of the pull request
-          base: branch_for_release_test # The base branch of the pull request
-          head: main # The head branch of the pull request
+          base: production # The base branch of the pull request
+          head: master # The head branch of the pull request
