Update create_pr3.yml

diff --git a/.github/workflows/create_pr3.yml b/.github/workflows/create_pr3.yml
--- a/.github/workflows/create_pr3.yml
+++ b/.github/workflows/create_pr3.yml
@@ -9,35 +9,35 @@ jobs:
   create-pr:
     runs-on: ubuntu-latest
 
-    steps:
-      # Step 1: Checkout the repository with full history
-      - name: Checkout repository
-        uses: actions/checkout@v2
-        with:
-          fetch-depth: 0 # Fetch all history for all branches and tags
+    # steps:
+    #   # Step 1: Checkout the repository with full history
+    #   - name: Checkout repository
+    #     uses: actions/checkout@v2
+    #     with:
+    #       fetch-depth: 0 # Fetch all history for all branches and tags
 
-      # Step 3: Check out the main branch and pull the latest changes
-      - name: Check out main branch
-        run: |
-          git checkout master
-          git pull origin master
+    #   # Step 3: Check out the main branch and pull the latest changes
+    #   - name: Check out main branch
+    #     run: |
+    #       git checkout master
+    #       git pull origin master
 
-      # Step 4: Check out the production branch and pull the latest changes
-      - name: Check out production branch
-        run: |
-          git checkout production
-          git pull origin production
+    #   # Step 4: Check out the production branch and pull the latest changes
+    #   - name: Check out production branch
+    #     run: |
+    #       git checkout production
+    #       git pull origin production
 
-      # Step 5: Merge changes from the main branch into the production branch
-      - name: Merge main branch into production
-        run: |
-          git merge master || { echo 'Merge failed'; exit 1; }
+    #   # Step 5: Merge changes from the main branch into the production branch
+    #   - name: Merge main branch into production
+    #     run: |
+    #       git merge master || { echo 'Merge failed'; exit 1; }
 
-      # Step 6: Push the merged changes to the production branch if merge was successful
-      - name: Push changes to production branch
-        if: success()
-        run: |
-          git push origin production
+    #   # Step 6: Push the merged changes to the production branch if merge was successful
+    #   - name: Push changes to production branch
+    #     if: success()
+    #     run: |
+    #       git push origin production
 
       # Step 7: Create a pull request to merge main into production
       - name: Create a pull request
